In [3]:
# flask
import flask # 웹서버 기능 5000번 port로 service

In [4]:
import matplotlib
import numpy as np

print(np.__version__)

def pprint(arr): # ndarray : numpy의 기본 데이터타입
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

arr = [1.0, 2.0, 3.0]    # list
a = np.array([1, 2, 3])  # np.array() : ndarray 생성 함수(매개변수:list)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1, dtype:int32
Array's Data:
 [1 2 3]


In [5]:
a = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9]) # ndarray
print(id(a)) # python core 주소값 확인
print(a.size)                    # 데이터 개수 (=10)

# 데이터타입 변경
# numpy는 행 중심, 동질적
print(a.astype(np.float32))      # =[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

# 전체 메모리 사이즈(byte)
print(a.dtype.itemsize * a.size) # =40

# iterator - for-in-range => list생성
#          - arange       => ndarray생성
a = np.arange(1000) # ndarray
a

2178139632144
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [8]:
# ndarray 초기화 함수들
print(np.zeros((3, 4))) # 모든 값이 0
print(np.ones((2,3,4), dtype=np.int16)) # 모든 값이 1, dtype에서 지정한 데이터타입으로 저장, 3차원(면,행,열)
print(np.full((2, 2), 7)) # 2*2을 모두 7로 채움
print(np.eye(4))          # 대각행렬 identity
print(np.empty((4,2)))    # 값을 초기화시키지 않음(메모리에 있는 쓰레기값으로 채워짐)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.94855038e-321]
 [1.33511969e-306 1.08221785e-312]]


In [36]:
a = np.arange(0, 100, 10)
indices = [1, 5, -1]
print(indices)

b = a[indices]
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [44]:
a = np.arange(11, 36) # 1차원
print(a) # -> 1차원

a.shape = (5,5) # 행렬은 정상 모양을 갖추어야한다. np.arange(11, 35) -> 행렬모양X
print(a) # -> 2차원

# python core에서의 함수
print(type(a))

# ndarray 속성
print(a.dtype)  # 데이터타입
print(a.size)   # 
print(a.shape)  # 차수 (=(5,5))
print(a.ndim)   # 차원 (=2)
print(a.nbytes) # =100bytes = 25개 * 4byte
print(a.strides) # 다음 열의 데이터는 몇 바이트를 건너뛰어야 하는가? =(20,4)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [47]:
arr = np.arange(10)
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12   # data update
print(arr[1:6])
print(arr)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]
[ 0  1  2  3  4 12 12 12  8  9]


In [170]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0])      # 0행
print(arr2d[0][2])   # 0행 2열
print(arr2d[0,2])  
print(arr2d[:2])     # 0,1행
print(arr2d)
print("----------------")
print(arr2d[:2, 1:]) # 모든 행의 1,2열
print("----------------")
print(arr2d[1, :2])  #
print(arr2d[2, :1])
arr2d[:2, :1] = 0
arr2d[:2, :1] = 0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
[[2 3]
 [5 6]]
----------------
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [173]:
# 행렬연산에서 <앞의 행렬>의 '열'수와 <뒤의 행렬>의 '행'수를 일치시켜야 행렬곱 가능
# 행렬곱에서 행렬 앞뒤로 바꾸면 안됨
print(np.ones((5), dtype=np.float64))
print(np.ones((4,5), dtype=np.float64))
print(np.ones((3,4,5), dtype=np.float64))
print("스트라이드의 값", np.ones((5), dtype=np.float64).strides) # 5열
print("스트라이드의 값", np.ones((4,5), dtype=np.float64).strides) # 4행 5열
print("스트라이드의 값", np.ones((3,4,5), dtype=np.float64).strides) # 3면 4행 5열
# 단일 데이터 float64 : 8 bytes 160
# (다음면까지의 크기, 다음행까지의 크기, 단일 데이터크기)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
스트라이드의 값 (8,)
스트라이드의 값 (40, 8)
스트라이드의 값 (160, 40, 8)


In [79]:
# 문제
arr3d = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ]) # 2면 2행 3열
print(arr3d.shape)
print("첫 면 = ", arr3d[0])
print("첫 차원 첫 행 =", arr3d[0,0])
print("첫 차원 첫 행 첫 요소는 = ", arr3d[0,0,0])

print(arr3d[1,0,1]) # = 8
print(arr3d[1,1,2]) # = 12

(2, 2, 3)
첫 면 =  [[1 2 3]
 [4 5 6]]
첫 차원 첫 행 = [1 2 3]
첫 차원 첫 행 첫 요소는 =  1
8
12


In [81]:
# arr3d = [ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ]
#old_values = arr3d # 같은 주소를 가리키고 있기 때문에 backup이 안됨
old_values = arr3d.copy() # copy()로 '값'만 복사시킴
arr3d[0] = 42

print("값의 변경 후")
print(arr3d) # 일반대입 = [ [[42,42,42], [42,42,42]], [[7,8,9], [10,11,12]] ]
             # copy()  = [ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ]

print("이전 값으로 복구")
arr3d = old_values
print(arr3d) # 일반대입 = [ [[42,42,42], [42,42,42]], [[7,8,9], [10,11,12]] ]
             # copy()  = [ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ]

값의 변경 후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [86]:
Z = np.arange(36) # 1차원으로 0~35
print(Z)

Z = Z.reshape((6,6)) # 6행 6열
print(Z)

reshape2 = Z.reshape((2,3,6)) # 2면 3행 6열
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [110]:
arr = np.arange(32).reshape((8,4))
print(arr)
print("-----------------------------")
print(arr[[1,5,7,2]]) # 행중심
print(arr[[-1,-5,-7,-2]]) # 거꾸로 indexing
print(arr[[1,5,7,2], [0,3,1,2]]) # 1행0열, 5행3열, 7행1열, 2행2열

# fancy indexing : 위에 있는 indexing의 단점을 보완한..
print("-----------------------------")
print(arr[[1,2,5,7]][:, [0,1,2,3]]) # 1,2,5,7행 모든 행에 대한 0,1,2,3열의 값 출력
print("-----------------------------")
print(arr[[1,5,7,2]][:, [0,3,1,2]])
print("-----------------------------")
# 1, 2, 5, 7
# [ 4  5  6  7]
# [ 8  9 10 11]
# [20 21 22 23]
# [28 29 30 31]

# 1, 5, 7, 2
# [ 4  5  6  7]
# [20 21 22 23]
# [28 29 30 31]
# [ 8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-----------------------------
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[ 4 23 29 10]
-----------------------------
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
-----------------------------
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
-----------------------------


In [60]:
arr = []
for i in range(6):
    ad = []
    for j in range(6):
        ad.append(i * 10 + j)
    arr.append(ad)
    
print(arr)
arr = np.array(arr)

print("주황색", arr[[0,1,2,3,4], [1,2,3,4,5]])
print("빨강색", arr[[0,2,5], 2])
print("하늘색", arr[3:6][:,[0,2,5]]) #arr[3:,[0,2,5]]

print("빨강색", arr[:,2])
print("주황색", arr[0, [3,4]])
print("연두색", arr[[2,4]][:, [0,2,4]])
print("초록색", arr[4:][:,[4,5]])


[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
주황색 [ 1 12 23 34 45]
빨강색 [ 2 22 52]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]
빨강색 [ 2 12 22 32 42 52]
주황색 [3 4]
연두색 [[20 22 24]
 [40 42 44]]
초록색 [[44 45]
 [54 55]]


In [72]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]]) # 4 X 3
x_tile = np.tile(x, (1,1))
print(x_tile)

v = np.array([1,0,1])
v_tile = np.tile(v, (4,1))
print(v_tile)

y = x + v_tile
print(y)

# 배열 연산 : 양쪽 차원이 일치해야함
print(x + v) # [4 X 3] + [1 X 3] => Broadcasting
print(x * -1) # 상수는 각 요소에 산술연산

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ -1  -2  -3]
 [ -4  -5  -6]
 [ -7  -8  -9]
 [-10 -11 -12]]


In [80]:
x = np.arange(6).reshape((3,2))
print(x)
# 거듭제곱 (행열곱)
# x @ x # Error : <앞의 행렬>의 '열'수와 <뒤의 행렬>의 '행'수가 일치해야한다.
# (3X2 * 3X2)
# => '전치행렬' 로 바꾸어준다.
print(x @ x.T) # 3X2 * 2X3
print(np.transpose(x))

[[0 1]
 [2 3]
 [4 5]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]
[[0 2 4]
 [1 3 5]]


In [86]:
arr = np.arange(24).reshape((2,3,4))
print(arr)
print("---------------------")
print(arr.transpose((1,0,2))) # 3면 2행 4열 ((2,3,4)의 index가 transpose의 매개변수로..)
print(arr.transpose((0,2,1))) # 2면 4행 3열

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
---------------------
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [93]:
# Boolean indexing(True/False)
names = np.array(["Seoul", "Daejun", "chungju", "seoul", "chungju", "Daejun", "Daejun"])
data = np.random.randn(7,4) # 7 X 4
print(data)
print(names == "Seoul") # 1, 0, 0, 0, 0, 0, 0
print("------------------------------------------------")
print(data[names == "Seoul"])
print(data[names == "Seoul", 2:])
print(data[names == "Seoul", 3])
print(names != "Seoul")
print(~(names != "Seoul"))
mask = (names == "Seoul") | (names == "chungju")
print(mask)
print(data[mask])

[[ 0.65448115 -0.08927985 -0.47607899  0.86185693]
 [ 2.13278737  0.08896943  0.60176032  0.17915405]
 [-0.82712682  0.06726743  0.10506972  2.12720133]
 [ 0.48296635  1.64774117  0.99822846 -0.39420074]
 [-0.367419   -1.61653179 -0.72016966 -0.54029579]
 [ 0.23575574 -0.95769868  1.35314449 -1.36815412]
 [-0.30678315 -1.14922148  0.56878136  0.43624154]]
[ True False False False False False False]
------------------------------------------------
[[ 0.65448115 -0.08927985 -0.47607899  0.86185693]]
[[-0.47607899  0.86185693]]
[0.86185693]
[False  True  True  True  True  True  True]
[ True False False False False False False]
[ True False  True False  True False False]
[[ 0.65448115 -0.08927985 -0.47607899  0.86185693]
 [-0.82712682  0.06726743  0.10506972  2.12720133]
 [-0.367419   -1.61653179 -0.72016966 -0.54029579]]


In [111]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr, yarr, cond)) # zip : 요소별로 같은 열의 데이터를 묶음
print(list(zip(xarr, yarr, cond)))

result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]
print("result = ", result)

# 위의 result를 함수화한 것이 np.where(cond, TRUE, FALSE)
result = np.where(cond, xarr, yarr) # cond가 참이면 X, 아니면 Y
print("result = ", result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0, 2, -2))

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result =  [1.1, 2.2, 1.3, 1.4, 2.5]
result =  [1.1 2.2 1.3 1.4 2.5]
[[ 1.309164   -0.64487572  1.53542626  0.34706532]
 [-0.42580421  0.56970293 -0.18295547 -0.92855896]
 [ 0.26126688  0.32379315 -0.39310448  1.5432903 ]
 [-0.6072234  -0.4033025  -1.20811287 -0.46236194]]
[[ 2 -2  2  2]
 [-2  2 -2 -2]
 [ 2  2 -2  2]
 [-2 -2 -2 -2]]


In [129]:
# 문제. 다음 데이터를 이용하여 두개 다 참일 때는 0, cond1이 참일 때는 1,
# cond2가 참일 때는 2, 그 외일때는 3으로 처리하여 출력하도록 하시요.
# 조건문은 4개, 삼항연산자는 3개
cond1 = np.array([1,0,1,1,0,0,1], dtype = bool)
cond2 = np.array([0,1,1,1,0,1,1], dtype = bool)
result1 = np.where(cond1, np.where(cond2, 0, 1), np.where(cond2, 2, 3))
result2 = np.where(cond1 & cond2, 0, np.where(~cond1 & ~cond2, 3, np.where(cond1, 1, 2)))
result3 = np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))
result4 = 1 * (cond1 & ~cond2) + 2 *(cond2 & ~cond1) + 3 * ~(cond1 | cond2)
print(result1)
print(result2)
print(result3)
print(result4)

[1 2 0 0 3 2 0]
[1 2 0 0 3 2 0]
[1 2 0 0 3 2 0]
[1 2 0 0 3 2 0]


In [136]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = np.zeros_like(x) # zeros_like: 다른 행렬과 size로 초기화
for i in range(10000):
    z[i] = x[i] + y[i]

print(x)
print(y)
print(z)


[    1     2     3 ...  9998  9999 10000]
[10001 10002 10003 ... 19998 19999 20000]
[10002 10004 10006 ... 29996 29998 30000]


In [145]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all(a == b)) # 전체가 참일 때 참
print(np.any(a == b)) # 하나라도 참이면 참
print(np.exp(a)) # 지수함수 : 자연대수(2.71828183)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [146]:
# 선형대수 
#  - 모든 문제를 선형으로 해결하자!! => 비선형도 잘게 나누면 선형이다.
# sin, cos -> 각도.. 주기..
# 크기가 1인 원..
# 호의 길이로 각도를 표현하자 => radian
# sin + cos => 소리

In [147]:
# 행렬의 종류
# - 정방행렬 : 정사각형(행과 열의 수가 같은 행렬)
# - 대칭행렬 : 우상단과 좌하단이 같은 행렬
# - 대각행렬 : scale을 변화시키는 요소
# - 단위행렬(indentity) : 행렬곱의 항등원(행렬*역행렬 = 단위행렬)
# - 역행렬 : 행렬의 나눗셈을 위해 곱해지는 행렬(정방행렬만 가능)
# - 특이행렬 : 역행렬이 없는 행렬...
# - 직교행렬 : 축의 정직교, 각 축간의 내적이 0인 행렬
# - 공분산행렬, 상관계수행렬, 거리행렬 : 정방행렬이면서 대칭행렬
# - 공분산 : 두 수 간의 관계. ((하나수-평균) * (다른수-평균)) / (n-1)
# - 상관계수 : (표준화 -1~1) : 공분산 / 표준편차의 곱


In [149]:
import numpy as np
F1 = np.array([[1,2], [3,4]])
F2 = np.array([[2,2], [2,2]])
print(F1)
print(F2)
print(F1 + F2)
print(F1 * F2)
print(F1 @ F2) # 행렬 곱도 내적 - 두 벡터의 사이각을 구해짐
               # 2개의 특성이 만들어짐
               # 2X2 * 2X3 -> 차원 확장
# 한꺼번에 차원축소를 하면 버려지는 차원이 많으면 손실이 큼
# 그래서 조금씩 여러번 축소할 필요가 있다 => deep learning

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [161]:
# 방정식의 해
# 2 x1 + x2 -2 x3 = -3
# 3 x1 +       x3 = 5
#   x1 + x2 -  x3 = -2
A = np.array([[2,1,-2], [3,0,1], [1,1,-1]])
print(A)
b = np.transpose(np.array([[-3,5,-2]])) # 열로 전치
print(b)

# np.linalg.solve: 역행렬을 내부적으로 구해서 행렬곱
# np.linalg.inv: 역행렬, np.dot, @: 행렬곱
x = np.linalg.solve(A, b) # A의 역행렬을 구해서 b와 곱해줌
print(x)
print(np.dot(np.linalg.inv(A), b)) # 행렬곱
print(np.linalg.inv(A) @ b) # 행렬은 나눗셈이 없으므로 역행렬을 곱함

# 검산 [1, -1, 2]
# 2 x1 + x2 -2 x3 = -3
# 3 x1 +       x3 =  5
#   x1 + x2 -  x3 = -2
print("검산결과 2*1 +(-1) -2 *2 =", 2*1 +(-1) -2 *2)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]
[[ 1.]
 [-1.]
 [ 2.]]
[[ 1.]
 [-1.]
 [ 2.]]
검산결과 2*1 +(-1) -2 *2 = -3


In [164]:
a = np.array([0,1,0])  # y축
b = np.array([1,0,0])  # x축
res = np.dot(a,b) # 내적 사이각 (내적=0 => 직각)
print(res)

print(np.linalg.norm(a)) # norm: 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a) * np.linalg.norm(b))
rad = res / (np.linalg.norm(a) * np.linalg.norm(b)) # =cos theta(radian)
print("cos theta", rad)
print(np.arccos(rad)) # =theta
print(np.degrees(np.arccos(rad))) # 각도

0
1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [166]:
x = np.array([[1,2], [3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [168]:
# 다음 방정식의 해를 구하고 검산하시요.
# x + y + z = 6
# 2y + 5z = -4
# 2x + 5y - z = 27
A = np.array([[1,1,1], [0,2,5], [2,5,-1]])
print(A)
b = np.transpose(np.array([[6,-4,27]])) # 열로 전치
print(b)
print(np.linalg.solve(A, b))

# x=5, y=3, z=-2 검산
# x + y + z = 5 + 3 - 2 = 6
# 2y + 5z = 2*3 + 5*(-2) = -4
# 2x + 5y - z = (2*5) + (5*3) - (-2) = 27

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]


array([[ 5.],
       [ 3.],
       [-2.]])